#apiVersion: v1
apiVersion: v1
kind: pod
metadata:
  name: nginx
  namespace: roboshop
  labels:
   name: nginx
   project: roboshop
spec:
  containers:
   - name: nginx
     image: nginx
  port:
   - containerPort: 80
  