apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
  lables:
    purpose: multiconatainer
spec:
 containers:
   - name: nginx
     image: nginx
   - name: almalinux
     image: almalinux:9
     command: ["sleep", "1000"]
