apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
   project: roboshop
   component: frontend
   environment: dev
   version: v1
spec:
 containers:
   - name: nginx
     image: nginx
     ports:
     - containerPort: 80